In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import seaborn as sns
sns.set()

# Pandas library is used for importing various file types e.g. csv, excel, json.
# also used for manipulation and cleaning dataframes.

# Numpy library has functions used for working with arrays and matrices
# faster, clearer and better quality code using Numpy

# Matplotlib is a 2D plotting library for visualising data in Python

# Statsmodels.api provides classes and functions for the estimation of many different statistical models,
# as well as for conducting statistical tests, and statistical data exploration

# Seaborn is used for improving Matplotlib visualisations to make them more visually attractive.
# It builds on top of MatPlotLib and works with Pandas for data structures

# sklearn is a library used for machine learning and statistical modeling.
# it includes many tools for classification, regression, clustering and dimensionality reduction

In [2]:
data = pd.read_csv("Life Expectancy Data .csv")
data

# importing and displaying the data

,Country,Year,Status,LifeExpectancy,AdultMortality,infantDeaths,Alcohol,PercentageExpenditure,HepatitisB,Measles,...,Polio,TotalExpenditure,Diphtheria,HIV,GDP,Population,Thinness1to19Years,Thinness5to9Years,IncomeCompositionOfResources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434,9.8

### Cleaning

In [3]:
data.isnull().sum()

# counts the number of null values in dataset by feature

Country                           0
Year                              0
Status                            0
LifeExpectancy                   10
AdultMortality                   10
infantDeaths                      0
Alcohol                         194
PercentageExpenditure             0
HepatitisB                      553
Measles                           0
BMI                              34
UnderFiveDeaths                   0
Polio                            19
TotalExpenditure                226
Diphtheria                       19
 HIV                              0
GDP                             448
Population                      652
Thinness1to19Years               34
Thinness5to9Years                34
IncomeCompositionOfResources    167
Schooling                       163
dtype: int64

In [4]:
data.isnull().sum().sum()

# counts the total number of null values in dataset

2563

In [5]:
data.fillna(data.mean())

# since there are many missing values (nulls), the mean of each collumn will be used to fill in the missing values
# (this may not be the best way to fill the missing values)

,Country,Year,Status,LifeExpectancy,AdultMortality,infantDeaths,Alcohol,PercentageExpenditure,HepatitisB,Measles,...,Polio,TotalExpenditure,Diphtheria,HIV,GDP,Population,Thinness1to19Years,Thinness5to9Years,IncomeCompositionOfResources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434,9.8

In [6]:
data = data.fillna(data.mean())

# storing the cleaned data into a new variable (data)

In [7]:
data_no_mv = data

# storing that variable in a new variable

In [8]:
data_no_mv.columns

# getting the columns from the dataset listed

Index(['Country', 'Year', 'Status', 'LifeExpectancy', 'AdultMortality',
       'infantDeaths', 'Alcohol', 'PercentageExpenditure', 'HepatitisB',
       'Measles', 'BMI', 'UnderFiveDeaths', 'Polio', 'TotalExpenditure',
       'Diphtheria', ' HIV', 'GDP', 'Population', 'Thinness1to19Years',
       'Thinness5to9Years', 'IncomeCompositionOfResources', 'Schooling'],
      dtype='object')

## Standardising

In [9]:
x = data_no_mv[['AdultMortality',
       'infantDeaths', 'Alcohol', 'PercentageExpenditure', 'HepatitisB',
       'Measles', 'BMI', 'UnderFiveDeaths', 'Polio', 'TotalExpenditure',
       'Diphtheria', ' HIV', 'GDP', 'Population', 'Thinness1to19Years',
       'Thinness5to9Years', 'IncomeCompositionOfResources', 'Schooling']]
y = data_no_mv['LifeExpectancy']

# separating the independant variables (x) from the dependant variable (Life expectancy/y)

In [10]:
from sklearn.preprocessing import StandardScaler

# importing a scaler from the sklearn library

In [11]:
scaler = StandardScaler()

# storing it in a variable

In [12]:
scaler.fit(x)

# fitting the standard scaler to the dependant variables

StandardScaler()

In [13]:
x_scaled = scaler.transform(x)

# storing the newly scaled values into a new variable (x_scaled)

In [14]:
x_scaled

array([[ 0.79158632,  0.26882378, -1.1729584 , ...,  2.77327898,
        -0.72540055, -0.57993072],
       [ 0.85607167,  0.28578638, -1.1729584 , ...,  2.81790246,
        -0.74005007, -0.61056961],
       [ 0.83188966,  0.30274898, -1.1729584 , ...,  2.86252595,
        -0.7693491 , -0.6412085 ],
       ...,
       [-0.73994077, -0.04498439, -0.04414645, ..., -0.79659991,
        -0.97932554, -0.61056961],
       [ 4.20124926, -0.04498439, -0.73624609, ..., -0.70735294,
        -0.97932554, -0.6718474 ],
       [ 4.03197521, -0.05346569, -0.74646158, ...,  1.41226265,
        -0.94514333, -0.6718474 ]])

## Creating Multiple Linear Regression

In [16]:
reg = LinearRegression()
reg.fit(x_scaled,y)

# storing the regression model in the variable (reg) and fitting it to the scaled dependant variables and the independant one

LinearRegression()

In [17]:
reg.coef_

# the numbers below represent the coefficient of each independant variable
# this is the constant that is multiplied by the variable

array([-2.52282307e+00,  1.17358973e+01,  4.75221623e-01,  2.66493507e-01,
       -3.18865654e-01, -2.34626029e-01,  8.64689327e-01, -1.19308307e+01,
        6.71204415e-01,  2.13854927e-01,  9.37690747e-01, -2.39386775e+00,
        4.81128299e-01,  2.33348716e-03, -3.65759996e-01,  2.72018880e-03,
        1.22731901e+00,  2.18552383e+00])

In [18]:
reg.intercept_

# the intercept is the point where the function crosses the y axis (the predicted value for y when x is 0)

69.22493169398906

In [19]:
reg.score(x_scaled,y)

#.score() returns the R-Squared of a linear regression (simple or multiple)

# however, the Adjusted R-Squared is more appropriate for multiple linear regerssion
# as it adjusts for multiple variables

0.8175560042141601

In [20]:
x_scaled.shape

# 2938 is the number of observations, and 18 the number of predictors (features)

(2938, 18)

In [21]:
r2 = reg.score(x,y)

# variable storing the R-Squared value


n = x.shape[0]

# the number of observations


p = x.shape[1]

# the number of predictors (18)


adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

# plugging in the variables into the R-Squared formula

-185021633.65389454

In [ ]:
# We can conclude that the Adjusted R Squared is significantly lower than the R Squared
# Therefore one or more of the predictors has little to no explanatory power
# To find out which predictors are the least important we use feature selection:

## Feature Selection

In [22]:
from sklearn.feature_selection import f_regression
f_regression(x_scaled,y)

# importing feature_selection module from sklearn library
# f_regression creates simple linear regressions of each feature
# applying the f_regression to the features (x) and target (y)

# first array shows F-statistics for each of the regressions
# Second array shows the corresponding P-values

(array([2.76404441e+03, 1.17962373e+02, 5.31781766e+02, 5.00991321e+02,
        1.27192318e+02, 7.47555807e+01, 1.33620149e+03, 1.52925260e+02,
        7.94861308e+02, 1.32741290e+02, 8.57392617e+02, 1.31687939e+03,
        6.67887756e+02, 1.13267385e+00, 8.42328652e+02, 8.17241347e+02,
        2.70508159e+03, 3.07202002e+03]),
 array([0.00000000e+000, 5.71450848e-027, 2.78146391e-108, 1.38444938e-102,
        6.57048596e-029, 8.61324481e-018, 1.94642951e-241, 2.79586247e-034,
        5.66704978e-155, 4.51844426e-030, 1.39163450e-165, 1.51847141e-238,
        7.22920497e-133, 2.87293240e-001, 4.82278222e-163, 8.62336187e-159,
        0.00000000e+000, 0.00000000e+000]))

In [23]:
p_values = f_regression(x_scaled,y)[1]
p_values

# storing the p-values from the regression in the variable 'p_values'

array([0.00000000e+000, 5.71450848e-027, 2.78146391e-108, 1.38444938e-102,
       6.57048596e-029, 8.61324481e-018, 1.94642951e-241, 2.79586247e-034,
       5.66704978e-155, 4.51844426e-030, 1.39163450e-165, 1.51847141e-238,
       7.22920497e-133, 2.87293240e-001, 4.82278222e-163, 8.62336187e-159,
       0.00000000e+000, 0.00000000e+000])

In [24]:
p_values.round(3)

# as the output is written in scientific notation, the p_values will be rounded to 3 digits

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.287, 0.   , 0.   , 0.   , 0.   ])

In [ ]:
# p_values above 0.05 or 5% are not significant, whereas below 0.05 are significant
# Therefore, it seems that most of these variables are significant except 'Population' (29%) so will drop that one

In [31]:
reg.drop(['Population'], axis=1)

AttributeError: 'LinearRegression' object has no attribute 'drop'

## Summary Table with P-values

In [32]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary

                        Features
0                 AdultMortality
1                   infantDeaths
2                        Alcohol
3          PercentageExpenditure
4                     HepatitisB
5                        Measles
6                            BMI
7                UnderFiveDeaths
8                          Polio
9               TotalExpenditure
10                    Diphtheria
11                           HIV
12                           GDP
13                    Population
14            Thinness1to19Years
15             Thinness5to9Years
16  IncomeCompositionOfResources
17                     Schooling

In [35]:
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values.round(3)

In [34]:
reg_summary

                        Features  Coefficients  p-values
0                 AdultMortality     -2.522823     0.000
1                   infantDeaths     11.735897     0.000
2                        Alcohol      0.475222     0.000
3          PercentageExpenditure      0.266494     0.000
4                     HepatitisB     -0.318866     0.000
5                        Measles     -0.234626     0.000
6                            BMI      0.864689     0.000
7                UnderFiveDeaths    -11.930831     0.000
8                          Polio      0.671204     0.000
9               TotalExpenditure      0.213855     0.000
10                    Diphtheria      0.937691     0.000
11                           HIV     -2.393868     0.000
12                           GDP      0.481128     0.000
13                    Population      0.002333     0.287
14            Thinness1to19Years     -0.365760     0.000
15             Thinness5to9Years      0.002720     0.000
16  IncomeCompositionOfResources      1.227319     0.000
17                     Schooling      2.185524     0.000